/**
 * Fonte unica dos termos bloqueados na descricao de ocorrencias.
 *
 * Mantenha aqui apenas termos cuja ocorrencia isolada seja inadequada com baixa
 * chance de uso legitimo. A normalizacao cuida de caixa, acentos, leetspeak e
 * repeticoes; por isso essas variacoes nao devem ser duplicadas nesta lista.
 */
export const TERMOS_BLOQUEADOS = [
  "abestado",
  "abestada",
  "abestalhado",
  "abestalhada",
  "arrombado",
  "arrombada",
  "babaca",
  "bocó",
  "boquete",
  "bosta",
  "bostinha",
  "buceta",
  "burro",
  "burra",
  "cacete",
  "carai",
  "caralho",
  "corno",
  "corna",
  "cretino",
  "cretina",
  "crl",
  "crlh",
  "cuzão",
  "desgraçado",
  "desgraçada",
  "escroto",
  "escrota",
  "fdp",
  "foda",
  "foda-se",
  "fodase",
  "fodendo",
  "foder",
  "fodeu",
  "fodido",
  "fodida",
  "imbecil",
  "idiota",
  "karalho",
  "krl",
  "merda",
  "mongoloide",
  "otário",
  "otária",
  "palhaço",
  "palhaça",
  "piroca",
  "porra",
  "pqp",
  "punheta",
  "puta",
  "puto",
  "retardado",
  "retardada",
  "safado",
  "safada",
  "sapatão",
  "siririca",
  "suruba",
  "tnc",
  "traveco",
  "trouxa",
  "vagabundo",
  "vagabunda",
  "viado",
  "viadinho",
  "vsf",
  "xereca"
] as const;

/** Expressoes avaliadas como sequencias completas de palavras. */
export const EXPRESSOES_BLOQUEADAS = [
  "enfia no cu",
  "filha da puta",
  "filho da puta",
  "macaco imundo",
  "pau no cu",
  "preto imundo",
  "puta que pariu",
  "tomar no cu",
  "vai se foder",
  "vai tomar no cu",
  "vá se foder"
] as const;
